// Generated by p2putils/tokengen, do not edit: token lists live in
// tokengen/HttpTokenGen.cpp, see build instructions there
#ifndef __LIBP2P_HTTPPARSECOMMON_H_
#define __LIBP2P_HTTPPARSECOMMON_H_

#ifdef __cplusplus
extern "C" {
#endif

// Reserved header ids: names the library recognizes with every recognition
// table - the built-in one (a NULL table argument) and every table built by
// httpHeaderTablePrepare (user lists may not contain these names). The
// parser interprets Content-Length and Transfer-Encoding (message framing),
// the rest are delivered with these ids for the client or a future library
// feature. Bit 30 keeps the values positive ints usable as C case labels
// and clear of the user id range [1, 0x3FFFFFFF]; hhUnknown (0) is reported
// for a valid name missing from the table.
enum {
  hhUnknown = 0,
  hhReservedBase = 0x40000000,
  hhContentLength,  // framing: the value is parsed as the body length
  hhTransferEncoding,  // framing: "chunked" detection
  hhContentEncoding,  // reserved for automatic decompression
  hhConnection,  // connection lifecycle: close / keep-alive / upgrade
  hhKeepAlive,  // keep-alive parameters
  hhHost,  // server-side validation and routing
  hhExpect,  // server-side 100-continue
  hhUpgrade,  // protocol switching (websocket, h2c)
  hhLocation   // client-side redirects
};

// Ids of the recognition table owned by the httpParseDefault callback (the
// asyncio http client installs that table via httpParseDefaultInit). The
// composition of the table is an implementation detail of the callback and
// may change in any release; the ids are ordinary user-range ids of that
// table, not reserved ones.
enum {
  hpdContentType = 1
};

// Request method tokens (RFC 9110: method names are case-sensitive);
// hmUnknown is reported for extension methods missing from the table
enum {
  hmUnknown = 0,
  hmGet,
  hmHead,
  hmPost,
  hmPut,
  hmDelete,
  hmConnect,
  hmOptions,
  hmTrace,
  hmPatch
};

#ifdef __cplusplus
}
#endif

#endif //__LIBP2P_HTTPPARSECOMMON_H_
