// Generated by p2putils/tokengen, do not edit: token lists live in
// tokengen/HttpTokenGen.cpp, see build instructions there
#ifndef __LIBP2P_HTTPPARSECOMMON_H_
#define __LIBP2P_HTTPPARSECOMMON_H_

#ifdef __cplusplus
extern "C" {
#endif

// Header name tokens, sorted alphabetically; hhUnknown is reported for names
// missing from the table. Values are compiled into both the library and its
// users: inserting a new name renumbers the tail, so a full rebuild of all
// library consumers is required after any change here.
enum {
  hhUnknown = 0,
  hhAccept = 1,
  hhAcceptCH,
  hhAcceptCharset,
  hhAcceptEncoding,
  hhAcceptLanguage,
  hhAcceptRanges,
  hhAccessControlAllowCredentials,
  hhAccessControlAllowHeaders,
  hhAccessControlAllowMethods,
  hhAccessControlAllowOrigin,
  hhAccessControlExposeHeaders,
  hhAccessControlMaxAge,
  hhAccessControlRequestHeaders,
  hhAccessControlRequestMethod,
  hhAge,
  hhAllow,
  hhAltSvc,
  hhAuthenticationInfo,
  hhAuthorization,
  hhCacheControl,
  hhConnection,
  hhContentDisposition,
  hhContentEncoding,
  hhContentLanguage,
  hhContentLength,
  hhContentLocation,
  hhContentRange,
  hhContentSecurityPolicy,
  hhContentType,
  hhCookie,
  hhDate,
  hhETag,
  hhExpect,
  hhExpires,
  hhForwarded,
  hhFrom,
  hhHost,
  hhIfMatch,
  hhIfModifiedSince,
  hhIfNoneMatch,
  hhIfRange,
  hhIfUnmodifiedSince,
  hhKeepAlive,
  hhLastModified,
  hhLink,
  hhLocation,
  hhMaxForwards,
  hhOrigin,
  hhPermissionsPolicy,
  hhPragma,
  hhPriority,
  hhProxyAuthenticate,
  hhProxyAuthenticationInfo,
  hhProxyAuthorization,
  hhRange,
  hhReferer,
  hhReferrerPolicy,
  hhRetryAfter,
  hhSecCHUA,
  hhSecCHUAMobile,
  hhSecCHUAPlatform,
  hhSecFetchDest,
  hhSecFetchMode,
  hhSecFetchSite,
  hhSecFetchUser,
  hhSecWebSocketAccept,
  hhSecWebSocketExtensions,
  hhSecWebSocketKey,
  hhSecWebSocketProtocol,
  hhSecWebSocketVersion,
  hhServer,
  hhServerTiming,
  hhSetCookie,
  hhStrictTransportSecurity,
  hhTE,
  hhTrailer,
  hhTransferEncoding,
  hhUpgrade,
  hhUpgradeInsecureRequests,
  hhUserAgent,
  hhVary,
  hhVia,
  hhWarning,
  hhWWWAuthenticate,
  hhXContentTypeOptions,
  hhXForwardedFor,
  hhXForwardedHost,
  hhXForwardedProto,
  hhXFrameOptions,
  hhXRealIP,
  hhXRequestedWith,
  hhXXSSProtection
};

// Request method tokens (RFC 9110: method names are case-sensitive);
// hmUnknown is reported for extension methods missing from the table
enum {
  hmUnknown = 0,
  hmGet,
  hmHead,
  hmPost,
  hmPut,
  hmDelete,
  hmConnect,
  hmOptions,
  hmTrace,
  hmPatch
};

#ifdef __cplusplus
}
#endif

#endif //__LIBP2P_HTTPPARSECOMMON_H_
